#include "kernel/os/os_time.h"
#include "os_util.h"
#include "los_sys.h"
#include "los_task.h"

#include <target_config.h>

/* system clock's frequency, OS ticks per second */
uint32_t OS_TickRateHz = LOSCFG_BASE_CORE_TICK_PER_SECOND;

OS_Time_t OS_GetTicks(void)
{
    return (OS_Time_t)LOS_TickCountGet();
}

OS_Time_t OS_GetTime(void)
{
    return (OS_Time_t)(LOS_TickCountGet() / OS_HZ);
}

void OS_MSleep(OS_Time_t msec)
{
    LOS_TaskDelay((UINT32)OS_MSecsToTicks(msec));
}

/* The fake random 32-bit value is generated by combining OS ticks and
 * the value of SysTick current value register.
 */
uint32_t OS_Rand32(void)
{
    return (uint32_t)(((*((volatile uint32_t *)0xE000E018)) & 0xffffff) |
                      (OS_GetTicks() << 24));
}
